### ISSUE TITLE
Additional Issues

### ISSUE THREAD

**Issue by ramess101** [ejmaginn/TransportCheckList#15]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

I have gone through the manuscript one more time and implemented some changes that I thought were pretty clear. However, there are a few issues that I wanted to discuss as a group:

1) The use of a final configuration from NVT for the NVE run. What if the final configuration is not a good representation of the desired temperature? I know this is the common approach, but is there a better method we can recommend? (Sec 4.1.1)
2) Should the off-diagonal terms be zero even for inhomogenous systems? (Sec 4.2.1)
3) What is the best practice for verifying that the time between time origins is longer than the correlation time? (Sec 4.2.1)
4) We use the term "long-time slope" in Sec 5.2.1 when we recommend using the "middle" time interval in Sec 5.2.2. What we mean is that we use the middle time to approximate the long-time slope, since at long times the noise increases. Is there a clearer way to say this?
5) What does "lag" mean in the context of Section 5.3.3? Is this the lag between time origins? The overall time that the VACF is computed? It was not obvious to me and we never use "lag" anywhere else.
6) Do we have a rationale for the required simulation time being an order of magnitude greater than the plateau time? We show that the 100 ps plateau requires at least a 1 ns trajectory, is that how we are justifying this statement? If so, we should state that explicitly. If not, is there a more rigorous explanation? (See Sec 6.1.2)
7) I included Ref 45 which is a recent publication regarding finite size effects (Sec 6.1.3). They demonstrate that for viscosity the system size effect is an oscillatory trend, so it is not possible (or necessary) to extrapolate to the infinite system limit. However, the final two sentences of Sec 6.1.3 (and a similar sentence in the Conclusions) recommends extrapolating to N^-1/3 = 0 if a linear trend is observed. However, from Ref 45 it is clear that this extrapolation would introduce significant errors into the estimation of eta because any linear trend would just be caused by an unfortunate sampling of the true oscillatory trend. Should we just remove the final two sentences of Sec 6.1.3 (and the corresponding sentence in the Conclusions) altogether?

**Comment by ramess101** [comment]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

Here are my thoughts regarding each issue:

1) Maybe recommend taking a configuration that has a temperature near the average temperature?
2) I don't know. But currently the manuscript appears to imply that they should be zero for both homogenous and inhomogenous.
3) Maybe we can reference the other Best Practices manuscript on sampling or some other article on determining correlation time?
4) I think we should modify the sentence in Sec 5.2.3 to read "We recommend that only the "middle" of the MSD be used in the fit to approximate the long-time slope."
5) ?
6) We can modify the statement to read: "the required simulation time should typically be around an order of magnitude greater than the plateau time, e.g., Figure 3 demonstrates that 1 ns trajectories are required for a plateau time of 100 ps."
7) I think we should just remove these statements altogether.

**Comment by ejmaginn** [comment]
@drroe @jrelliottoh @ramess101 @dcarls0n 

I went through the revision carefully - thanks for using the diff feature! Let me respond to 1-7 items listed and then add a few of my own suggestions:
1. One suggestion is to take the last configuration, do aggressive velocity rescaling for a short time, then run NVE throwing out the first few ps. Then you can use the remainder for the production run. 

2. I don't think you can be sure the off-diagonal components will be zero in an inhomogeneous system; for example, in a porous material with tortuous pores, there will be correlation between motion in different directions. They must be zero for a homogeneous system. 

3. Rich is right - ref. 33 covers this. We should refer to it. 

4. I agree with Rich's statement.

5. I think this is referring to time between origins but it IS unclear. Not sure how this got in there. We could remove without hurting things. 

6. Rich's statement is OK. I think this was an empirical observation for one system and is not necssarily general.

7. I agree with Rich.

Very small corrections (I did not make as I didn't want to mess up version control). Could you make these changes Rich?

a. 2nd column page 2: add a comma between California and Santa Barbara
b. page 6 column 1 3rd line sec 4.1.2: I think "seed" should be "seeds"
c. Section 4.2.3 is very good but there is no reference given. Is there a good general reference for describing bootstrapping?
d. page 8 1st column, 3rd line from end of sec 5: self-diffusivity constant => self-diffusion coefficient.
e. page 13 discussion after eqn 4: We recommend using all six terms, but we imply that there is some disagreement about the denominator (10 or something else: refs 36, 27, 48 and 18). I was unaware of this controversy. Should we then not recommend 6 and just say use 3 until the controversy is resolved? Seems this makes a big difference.
f. page 18, 1st column, 2nd paragraph of Sec. 7: We say NVE is preferred over NVT, but we also say earlier in the paper that it might not matter. A bigger thing to emphasize is not to use NPT. Could we reword this sentence: "...the NVE ensemble is recommended, although the NVT ensemble has been shown to also give accurate diffusivities. We discourage the use of the NPT ensemble due to the potential interference of the barostat in self-diffusivity prediction."

**Comment by ramess101** [comment]
@ejmaginn 

Thanks for the feedback. @drroe @jrelliottoh @dcarls0n any thoughts? Specifically, does anyone disagree with the following decisions:

1) Leave the NVE suggestion as is (unless we feel like it deserves a more rigorous recommendation like that presented by Ed above)
2) Make it clear that the statement about the off-diagonal elements being zero applies only to homogenous systems
3) Reference Ref 33 regarding correlation times
4) Change to "We recommend that only the "middle" of the MSD be used in the fit to approximate the long-time slope."
5) Reword this sentence. First we need to know exactly what the original intent was. Does anyone know what lag refers to?
6) Include some rationale regarding the order of magnitude longer run. Unless we have a better justification, we can just say, "e.g., Figure 3 demonstrates that 1 ns trajectories are required for a plateau time of 100 ps."
7) Remove sentences regarding extrapolation for viscosity finite size effects

Regarding Ed's comments:

a. Add comma
b. Change to "seeds"
c. I have one I can add. This will also help address one of the editor's comments about some missing references.
d. Change to "self-diffusion coefficient"
e. I don't think it really makes that big of a difference. This all comes down to how much you want to weight the different terms. Different weights require different normalization constants, but if all terms are pretty similar then the average will be similar regardless. I feel like we can leave this since we do make the disclaimer that three terms is likely good enough anyways.
f. I think we should make this change because we do recommend both NVE and NVT but strongly discourage NPT. 

I will upload Ed's simple changes soon. Once we resolve the few outstanding issues (mainly 5, 6, and e), I will implement those final changes.

**Comment by drroe** [comment]
> 5. What does "lag" mean in the context of Section 5.3.3? Is this the lag between time origins? The overall time that the VACF is computed? It was not obvious to me and we never use "lag" anywhere else.

Yes, it is the lag between time origins. For each value of lag, as the value increases the number of data points you have for a finite data set decreases, which eventually starts to increase your statistical noise (e.g. if you have a data set of 10 points you have 9 values for lag = 1 but only 1 value for lag = 9) - this is typically what leads to the tails of these functions being poorly behaved. I'm not sure if there is one definitive rule on how to choose the maximum lag to minimize statistical uncertainty; I've seen more rigorous statistical methods employed (like the Bayesian information criterion etc), log-likelihood, and so on, but personally I haven't found them all that necessary in the context of calculating the VACF (but maybe someone else here has had different experiences).

Essentially you want the max lag to be large enough so that you have good statistics, but not so large that you start introducing extra noise. The real criterion I suppose should be that the VACF properly converges to zero at longer times. So maybe we should rewrite that part of 5.3.3 to be something like:

Note that when calculating the VACF, care must be taken to ensure that the function properly converges to 0 at long times, since the long time "tail" of the VACF can contribute significantly to the integral. For water this happens on the order of ps, but other molecules may require longer times. A good rule of thumb for ensuring that the calculated VACF has been sampled adequately is to simulate from up to twice as long as to an order of magnitude longer than the estimated decay-to-zero time, then determine the VACF using a maximum lag up to half the total simulation time. 

This probably can be said a bit more eloquently, but is that at least more clear than what is currently in the doc?

**Comment by ramess101** [comment]
@drroe 

Thank you. That did clarify the issue, although I am still struggling to find a best way to integrate that into this section. I feel like this should actually go in the "simulation length" discussion where we talk about time origins. Does that sound good? I have two revised statements, what do you think?

Version 1:

Note that when calculating the VACF, care must be taken to ensure that the function properly converges to 0 at long times, since the long-time "tail" of the VACF can contribute significantly to the integral [10].  Depending on the system dynamics, the decay-to-zero time may range between 1 and 100 ps [@drroe do you have a better range that we can provide? And do you have any references for this?]. A good rule of thumb for ensuring that the calculated VACF has been sampled adequately is to perform simulations that are a factor of 2 to 10 times longer than the estimated decay-to-zero time. The elapsed time between subsequent time origins (often referred to as the "lag") should then not exceed half the total simulation time.

Version 2:

Note that when calculating the VACF, care must be taken to ensure that the function properly converges to 0 at long times, since the long-time "tail" of the VACF can contribute significantly to the integral [10].  Depending on the system dynamics, the decay-to-zero time may range between 1 and 100 ps [@drroe do you have a better range that we can provide? And do you have any references for this?]. The elapsed time between subsequent time origins (often referred to as the "lag") should be large enough that the VACF converges to 0 but not too large, as this introduces noise from the long-time tail. A good rule of thumb for ensuring that the calculated VACF has been sampled adequately is to perform simulations that are a factor of 2 to 10 times longer than the estimated decay-to-zero time. The lag should then not exceed half the total simulation time.

If I have changed the meaning of your original statement, please revise your preferred version and send back. Again, I think we should move this to the end of Section 5.3.2. Let me know what you think.

**Comment by drroe** [comment]
>  I feel like this should actually go in the "simulation length" discussion where we talk about time origins.

That seems good.

> Depending on the system dynamics, the decay-to-zero time may range between 1 and 100 ps

I wouldn't actually give a specific range here. Water is a common thing to simulate, and the VAC time is well known to be on the order of ps so I don't think we need a reference here (if we do, I think Rahman and Stillinger did some theoretical work on it back in the 70s, I'll need to look a bit to dig up the reference). However, the VACF will decay very differently for more complex molecules. I think it's probably enough that we tell people to simulate until they are sure the tail of the VACF is converged to 0.

**Comment by ramess101** [comment]
@drroe 

OK, I will look into Rahman and Stillinger to have a reference for water. I agree that we don't need to provide a specific range, rather we just need to recommend that they confirm that the tail has converged. I will post the revised section before the end of the day.

**Comment by ramess101** [comment]
@drroe 

This reference is probably good enough:

![image](https://user-images.githubusercontent.com/23408516/44811935-2723cd00-ab93-11e8-9544-0d1138abb279.png)

![image](https://user-images.githubusercontent.com/23408516/44811941-2ab75400-ab93-11e8-9dd5-028e60b6b657.png)

**Comment by ramess101** [comment]
@drroe @ejmaginn @dcarls0n @jrelliottoh 

Here are three different versions of this paragraph (versions 1 and 2 only have a single sentence different, but version 3 is considerably different). Can we get a vote on which paragraph is the most clear and has the most logical order? Along with voting on your favorite, please provide any feedback for how to improve them.

For context, this is the preceding paragraph:

![image](https://user-images.githubusercontent.com/23408516/44814460-027f2380-ab9a-11e8-8553-0f2c2367d3ab.png)

Version 1:

![image](https://user-images.githubusercontent.com/23408516/44814486-14f95d00-ab9a-11e8-80c8-632b90ce22d3.png)

Version 2:

![image](https://user-images.githubusercontent.com/23408516/44814550-496d1900-ab9a-11e8-8cc7-05a352ae4392.png)

Version 3:

![image](https://user-images.githubusercontent.com/23408516/44814498-1dea2e80-ab9a-11e8-94db-a527a74d1a30.png)

**Comment by ramess101** [comment]
@ejmaginn @drroe @jrelliottoh @dcarls0n 

My vote is for version 3, because it flows more naturally from the previous paragraph where we mention time origins. However, I don't love that the example for water is just thrown on at the end. Between versions 1 and 2, I like the wording of version 2 more (ignoring the small typo I just noticed).

**Comment by ejmaginn** [comment]
@drroe @ramess101 @jrelliottoh @dcarls0n I also like version 3. I agree the water reference in the last line seems like a throwaway. We could just cut that last line and be OK.

**Comment by drroe** [comment]
> We could just cut that last line and be OK.

I'm OK with that, or with expanding it to be a full example:

"For example, water models at liquid conditions typically exhibit a decay to zero time on the order of 1 ps, so a simulation of 10-20 ps should be sufficient for cacluating the VACF."

**Comment by ramess101** [comment]
@ejmaginn @drroe 

OK, I have revised this section (see below). Here are the main changes:

1) Moving one of the VACF sentences to the data analysis section
2) Bulking up the water model example
3) Rewording the "lag" sentences 

One question, @drroe , is the 10-20 ps statement consistent with the recommendation of performing simulations from 2 to 10 times the decay-to-zero time? Shouldn't we say, "a simulation of 2 to 10 ps should be sufficient ..."?

![image](https://user-images.githubusercontent.com/23408516/44855016-597f0a00-ac27-11e8-8823-8d2277df2a55.png)

**Comment by ramess101** [comment]
@drroe 

How does this sound (changed 10-20 to 2-10 and included lag time):

For example, water models at liquid conditions typically exhibit a decay-to-zero time on the order of 1 ps, such that a simulation of 2 to 10 ps with a lag time no greater than 1 ps should be sufficient for obtaining a well converged VACF (see Figures 12-15 of Ref. [43]).

**Comment by drroe** [comment]
Thinking about it a bit more, we should probably recommend that the simulation time be an order of magnitude more than the decay time (the better to ensure good long-time tail behavior/convergence) and then double that to try to ensure good statistics when actually calculating the VAC function - does that make sense? So in the case of water it would be 20 ps.

**Comment by ramess101** [comment]
OK, is this what the changes should look like? (Changes are in bold)

A good rule of thumb for ensuring that the calculated VACF has been sampled adequately is to perform simulations that are **approximately** a factor of **20** times longer than the estimated decay-to-zero time. The lag between time origins should then **be greater than the decay-to-zero time but** not exceed half the total simulation time. For example, water models at liquid conditions typically exhibit a decay-to-zero time on the order of 1 ps, such that a simulation of **20 ps** with a lag time **between 1 and 10 ps** should be sufficient for obtaining a well converged VACF

**Comment by ejmaginn** [comment]
@ramess101 @drroe  This reads well to me.

**Comment by ramess101** [comment]
Here are @jrelliottoh remarks:

5. I didn’t write that sentence and I don’t know where it came from. If its origin and meaning can’t be resolved, I would say we should scratch it.

6. I think your modification makes the guideline viable. It implies that the basis for the guideline is sparse and empirical so it is open to revision if additional evidence comes along. That seems fine to me.

e. I concur with leaving it and noting the competing perspectives in the literature.
